import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Link from 'next/link';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} ${geistMono.className} antialiased`}
      >
        <div className="z-[800]">
          <h1>Choose a Map</h1>
          <ul>
            <li>
              <Link href="/map1">Map 1</Link>
            </li>
            <li>
              <Link href="/map2">Map 2</Link>
            </li>
          </ul>
        </div>
        <main className="h-dvh">{children}</main>
      </body>
    </html>
  );
}
